[api]
enabled = true
address = "0.0.0.0:8686"

#[sources.demo_logs]
#type = "demo_logs"
#interval = 1.0
#format = "json"

[sources.lc]
type = "socket"
address = "0.0.0.0:6514"
max_length = 102_400
mode = "tcp"

[transforms.lctransform]
type = "remap"
inputs = ["lc"]
source = """
parsed, err = parse_syslog(.message)
if err == null {
  . |= parsed
}
. = parse_json!(string!(.message))
"""

[sinks.console]
inputs = ["lctransform"]
target = "stdout"
type = "console"
encoding.codec = "json"

[sinks.loki]
type = "loki"
inputs = [  "lctransform"]
endpoint = "${LOKIENDPOINT}"
compression = "snappy"

[sinks.loki.labels]
#forwarder = "vector"
event = "{{ .routing.event_type }}"
host = "{{ .routing.hostname }}"

#message = "{{ message }}"

[sinks.loki.encoding]
codec = "json"
  
[sinks.loki.auth]
password = "${LOKIPASS}"
strategy = "basic"
user = "${LOKIUSER}"

[sinks.loki.tls]
verify_certificate = false
