[api]
enabled = true
address = "0.0.0.0:8686"

#[sources.demo_logs]
#type = "demo_logs"
#interval = 1.0
#format = "json"

[sources.lc]
type = "syslog"
address = "0.0.0.0:6514"
max_length = 102_400
mode = "tcp"

#[transforms.parse_logs]
#type = "remap"
#inputs = ["demo_logs"]
#source = '''
#. = parse_syslog!(string!(.message))
#'''

[sinks.console]
inputs = ["lc"]
target = "stdout"
type = "console"
encoding.codec = "json"

[sinks.loki]
type = "loki"
inputs = [  "lc"]
endpoint = "${LOKIENDPOINT}"
compression = "snappy"

[sinks.loki.labels]
#forwarder = "vector"
service = "{{ appname }}"
host = "{{ host }}"
#message = "{{ message }}"

[sinks.loki.encoding]
codec = "json"
  
[sinks.loki.auth]
password = "${LOKIPASS}"
strategy = "basic"
user = "${LOKIUSER}"

[sinks.loki.tls]
verify_certificate = false
